### ISSUE TITLE
count error with windows line seperator \r\n

### ISSUE THREAD

**Issue by yougg** [bytbox/sloc#2]
user@host:/tmp$ echo -e '// a\n\n// b\n\n// c' > test.h
user@host:/tmp$ cat -A test.h 

```
// a$
$
// b$
$
// c$
```

user@host:/tmp$ sloc test.h 

```
  Language  Files  Code  Comment  Blank  Total
     Total      1     0        3      2      5
         C      1     0        3      2      5
```

user@host:/tmp$ unix2dos test.h 
unix2dos: converting file test.h to DOS format ...
user@host:/tmp$ cat -A test.h 

```
// a^M$
^M$
// b^M$
^M$
// c^M$
```

user@host:/tmp$ sloc test.h 

```
  Language  Files  Code  Comment  Blank  Total
     Total      1     2        3      0      5
         C      1     2        3      0      5
```

**Comment by bytbox** [comment]
If I'm understanding correctly, the issue is that sloc is considering a 'line' consisting of just '\r' to be a code line? Does that make sense with what you've observed?

(... I wrote this code ages ago, but surely \r should count as whitespace...)

**Comment by bytbox** [comment]
Ah, it looks like line 124 is the culprit. I'm not using any sort of golang 'is_whitespace' function. Will fix; thanks for the report!

**Comment by bytbox** [comment]
Please note that the up-to-date version of this code is http://git.bytbox.net/sloc. I've fixed this bug there, too.

**Comment by yougg** [comment]
update and test ok, thanks. :smile:
