### ISSUE TITLE
Installation error - insecure protocol

### ISSUE THREAD

**Issue by paulvollmer** [bytbox/sloc#6]
if i run the installation command from the readme, i get an error:

```
package git.bytbox.net/sloc.git/sloc: cannot download, git://git.bytbox.net/sloc uses insecure protocol
```

it works with the common go get github... command

```
go get github.com/bytbox/sloc/sloc
```

thanks for the helpful tool...

**Comment by bytbox** [comment]
Yeah, bytbox.net no longer exists, and I forgot to change the README. Thanks for pointing this out.
